import MlmcLean

/-! Axiom audit: every theorem below must depend only on `propext`, `Classical.choice`,
`Quot.sound` (the standard Lean/Mathlib axioms) — in particular no `sorryAx`. -/

#print axioms MLMC.cost_lower_bound
#print axioms MLMC.lagrangeN_variance_cost
#print axioms MLMC.lagrangeN_unique
#print axioms MLMC.optimal_cost_isLeast
#print axioms MLMC.optimal_variance_isLeast
#print axioms MLMC.twoLevel_optimal_ratio
#print axioms MLMC.optimalN_variance
#print axioms MLMC.optimalN_cost
#print axioms MLMC.mse_eq_variance_add_sq_bias
#print axioms MLMC.mlmc_mean
#print axioms MLMC.mlmc_variance
#print axioms MLMC.mlmc_mse
#print axioms MLMC.sum_integral_levelDiff
#print axioms MLMC.exists_L_N
#print axioms MLMC.mlmc_complexity_core
#print axioms MLMC.variance_sample_mean
#print axioms MLMC.giles_theorem1
#print axioms MLMC.giles_theorem1_cost_sum
#print axioms MLMC.giles_theorem1_uniform
#print axioms MLMC.giles_theorem1_of_core
#print axioms MLMC.giles_theorem1_isBigO
#print axioms MLMC.integral_levelEstimator
#print axioms MLMC.variance_levelEstimator
#print axioms MLMC.indepFun_levelEstimator
#print axioms MLMC.mlmcEstimator_mean_variance
#print axioms MLMC.giles_theorem1_standard
#print axioms MLMC.exists_iid_inputs
#print axioms MLMC.giles_theorem1_iid
#print axioms MLMC.integral_blockMean
#print axioms MLMC.variance_blockMean
#print axioms MLMC.indepFun_blockMean
#print axioms MLMC.integral_comp_level
#print axioms MLMC.integral_cost_level
#print axioms MLMC.integral_singleTerm
#print axioms MLMC.singleTerm_unbiased
#print axioms MLMC.singleTerm_variance
#print axioms MLMC.singleTerm_variance_ge
#print axioms MLMC.summable_of_memLp_singleTerm
#print axioms MLMC.randomised_necessary
#print axioms MLMC.singleTermN_mean_variance
#print axioms MLMC.randomised_summable
#print axioms MLMC.randomised_not_summable
#print axioms MLMC.randomised_optimal_p
#print axioms MLMC.randomised_optimal_p_eq
#print axioms MLMC.randomised_optimal_p_isLeast
#print axioms MLMC.randomised_mlmc_finite
#print axioms MLMC.sum_crossDiff
#print axioms MLMC.slab_bound
#print axioms MLMC.tail_bound
#print axioms MLMC.inner_bound
#print axioms MLMC.mimc_complexity_core
#print axioms MLMC.mimc_complexity
#print axioms MLMC.mimc_complexity_boundary
#print axioms MLMC.integrable_integral_crossDiff
#print axioms MLMC.tendsto_sum_box_integral_crossDiff
#print axioms MLMC.hasSum_integral_crossDiff
#print axioms MLMC.mimc_mse_cost
#print axioms MLMC.giles_theorem2
#print axioms MLMC.giles_theorem2_boundary
#print axioms MLMC.mimcD3_eq_zero
#print axioms MLMC.giles_theorem2_full
#print axioms MLMC.nested_cost_lower_bound
#print axioms MLMC.nested_optimal_allocation
#print axioms MLMC.nested_cost_isLeast
#print axioms MLMC.nested_saving
#print axioms MLMC.nestedEstimator_mean_variance
#print axioms MLMC.nestedCost_mean
#print axioms MLMC.nested_mlmc_mse
#print axioms MLMC.mc_estimate
#print axioms MLMC.controlVariate_mean
#print axioms MLMC.controlVariate_variance
#print axioms MLMC.controlVariate_optimal
#print axioms MLMC.controlVariate_estimator
#print axioms MLMC.optimal_cost_const_product
#print axioms MLMC.optimal_cost_increasing
#print axioms MLMC.optimal_cost_decreasing
#print axioms MLMC.mse_lt_of_half
#print axioms MLMC.weak_rate_of_second_moment
#print axioms MLMC.allocation_eq_3_1
#print axioms MLMC.remaining_error
#print axioms MLMC.convergence_test_mse
#print axioms MLMC.consistency_mean
#print axioms MLMC.covariance_sq_le
#print axioms MLMC.sqrt_variance_add_le
#print axioms MLMC.sqrt_variance_sub_le
#print axioms MLMC.consistency_sd
#print axioms MLMC.sampleVariance_sd
#print axioms MLMC.kurtosis_of_ternary
#print axioms MLMC.tendsto_kurtosis_atTop
#print axioms MLMC.levelKeep_product
#print axioms MLMC.levelDrop_test
#print axioms MLMC.levelDrop_variance
#print axioms MLMC.levelDrop_perfect_correlation
#print axioms MLMC.levelDrop_uncorrelated
#print axioms MLMC.integral_fineCoarseDiff
#print axioms MLMC.integral_antitheticDiff
#print axioms MLMC.giles_theorem1_corrections
#print axioms MLMC.giles_theorem1_fineCoarse
#print axioms MLMC.giles_theorem1_antithetic
#print axioms MLMC.richardson_extrapolation
#print axioms MLMC.ml2r_weights
#print axioms MLMC.ml2r_moment_succ
#print axioms MLMC.ml2r_bias_eq
#print axioms MLMC.ml2r_bias
#print axioms MLMC.ml2r_rearrange
#print axioms MLMC.ml2r_estimator_mean_variance
#print axioms MLMC.multiOutput_variance
#print axioms MLMC.multiOutput_optimal
#print axioms MLMC.integral_norm_add_sq_of_indepFun
#print axioms MLMC.integral_add_sq_of_indepFun
#print axioms MLMC.integral_norm_sum_sq_of_indepFun
#print axioms MLMC.integral_norm_sub_sq_eq
#print axioms MLMC.mlmc_mse_hilbert
#print axioms MLMC.giles_theorem1_hilbert
#print axioms MLMC.sq_norm_add_of_indepFun_fails_sup
#print axioms MLMC.abs_sub_roundFixed_le
#print axioms MLMC.roundFixed_mantissa
#print axioms MLMC.integral_sq_roundError_le
#print axioms MLMC.integral_sq_of_isUniform
#print axioms MLMC.integral_sq_uniform_roundError
#print axioms MLMC.variance_sum_eq
#print axioms MLMC.variance_le_integral_sq
#print axioms MLMC.variance_sum_mul_le_of_indep
#print axioms MLMC.variance_linearised_indep
#print axioms MLMC.variance_sum_le_sq_sum_sqrt
#print axioms MLMC.sqrt_variance_mul_le
#print axioms MLMC.variance_linearised_corr
#print axioms MLMC.vIndep_le_vCorr
#print axioms MLMC.variance_extended_indep
#print axioms MLMC.variance_extended_corr
#print axioms MLMC.opCost_le_sepCost
#print axioms MLMC.levelwise_optimisation
#print axioms MLMC.vIndepR_natCast
#print axioms MLMC.hasDerivAt_vIndepR_update
#print axioms MLMC.hasDerivAt_sepCost_update
#print axioms MLMC.exists_unique_bitWidth
#print axioms MLMC.hasDerivAt_levelCost
#print axioms MLMC.levelCost_stationary_iff
#print axioms MLMC.vIndepR_antitone
#print axioms MLMC.greedy_rounding_feasible
-- helper lemmas that the prove2.me generator promotes to nodes
#print axioms MLMC.sqrt_Vb_mul_Cb
#print axioms MLMC.two_rpow_levelL_le
#print axioms MLMC.tail_cost_bound
#print axioms MLMC.setIntegral_level
#print axioms MLMC.hasSum_measureReal_level
#print axioms MLMC.sq_tsum_le_tsum_sq_div
#print axioms MLMC.card_filter_slab_le
#print axioms MLMC.card_filter_mul_le
#print axioms MLMC.one_add_rpow_le_exp
#print axioms MLMC.neg_log_rpow_mul_rpow_le
#print axioms MLMC.sum_box_two_rpow_le_prod
#print axioms MLMC.sum_piFinset_succ
#print axioms MLMC.mimc_exists_level
#print axioms MLMC.mimc_construction
#print axioms MLMC.mimc_level_power
#print axioms MLMC.mimc_extra_term
